#     @author: Matteo Caruso
#     @email: matteo.caruso@phd.units.it
#     @email: matteo.caruso1993@gmail.com

body:
    geometry:
        body_length: 0
        body_width: 0
        body_heigth: 0
        
    inertial:
        mass: 1
        inertia:
            ixx: 1.71402
            iyy: 0.8856
            izz: 2.5725
            ixy: 0
            ixz: 0
            iyz: 0

        origin:
            position:
                x: 0
                y: 0
                z: 0
            orientation:
                roll: 0
                pitch: 0
                yaw: 0

    visual:
        mesh: true
        mesh_scale:
            x: 0.001
            y: 0.001
            z: 0.001
        filename: "body_master.STL"
        origin_mesh:
            position:
                x: 0
                y: 0
                z: 0
            orientation:
                roll: 0
                pitch: 0
                yaw: 0
            
        origin_simple_geom:
            position:
                x: 0
                y: 0
                z: 0
            orientation:
                roll: 0
                pitch: 0
                yaw: 0



    collision:
        active: false
        mesh: false
        filename: "body_master.STL"


joint:
    type: "fixed"
    origin:
        position:
            x: 0
            y: 0
            z: 0

        orientation:
            roll: 0
            pitch: 0
            yaw: 0
    