# @author: Matteo Caruso
# @email: matteo.caruso@phd.units.it
# @email: matteo.caruso1993@gmail.com
Archimede:
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 100